// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { QueryOperationTypes as PgAdapterQueryOps } from '@prisma/orm-postgres/adapter/operation-types';
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';

import type {
  ContractWithTypeMaps,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'da06cd8aaa95cd2a12b6ec7af3ccd003366dcdaa88e3c78dfd5578ecf323459a'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgAdapterQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly AgentAdmission: {
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly clientMessageId: CodecTypes['pg/text@1']['output'];
      readonly kind: CodecTypes['pg/text@1']['output'];
      readonly operationId: CodecTypes['pg/text@1']['output'] | null;
      readonly identityId: CodecTypes['pg/text@1']['output'];
      readonly payer: CodecTypes['pg/text@1']['output'];
      readonly requestDigest: CodecTypes['pg/text@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
      readonly rejectionReason: CodecTypes['pg/text@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly quotaUsageDate: CodecTypes['pg/date-string@1']['output'] | null;
      readonly quotaReservedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly quotaRefundedAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly AgentOpenOperation: {
      readonly operationId: CodecTypes['pg/text@1']['output'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['output'];
    };
    readonly AgentSettlement: {
      readonly operationId: CodecTypes['pg/text@1']['output'];
      readonly lastUsageSeq: CodecTypes['pg/int8number@1']['output'];
      readonly settledAt: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly PiListValue: {
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly namespace: CodecTypes['pg/text@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly value: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly PiRecord: {
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly kind: 'entry' | 'usage';
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
    };
    readonly PiScalarValue: {
      readonly sessionId: CodecTypes['pg/text@1']['output'];
      readonly namespace: CodecTypes['pg/text@1']['output'];
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly value: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly PiSession: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/jsonb@1']['output'];
      readonly nextSeq: CodecTypes['pg/int8number@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly AgentAdmission: {
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly clientMessageId: CodecTypes['pg/text@1']['input'];
      readonly kind: CodecTypes['pg/text@1']['input'];
      readonly operationId: CodecTypes['pg/text@1']['input'] | null;
      readonly identityId: CodecTypes['pg/text@1']['input'];
      readonly payer: CodecTypes['pg/text@1']['input'];
      readonly requestDigest: CodecTypes['pg/text@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
      readonly rejectionReason: CodecTypes['pg/text@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly quotaUsageDate: CodecTypes['pg/date-string@1']['input'] | null;
      readonly quotaReservedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly quotaRefundedAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly AgentOpenOperation: {
      readonly operationId: CodecTypes['pg/text@1']['input'];
      readonly createdAt: CodecTypes['pg/timestamptz-string@1']['input'];
    };
    readonly AgentSettlement: {
      readonly operationId: CodecTypes['pg/text@1']['input'];
      readonly lastUsageSeq: CodecTypes['pg/int8number@1']['input'];
      readonly settledAt: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly PiListValue: {
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly namespace: CodecTypes['pg/text@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly value: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly PiRecord: {
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly kind: 'entry' | 'usage';
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
    };
    readonly PiScalarValue: {
      readonly sessionId: CodecTypes['pg/text@1']['input'];
      readonly namespace: CodecTypes['pg/text@1']['input'];
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly value: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly PiSession: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/jsonb@1']['input'];
      readonly nextSeq: CodecTypes['pg/int8number@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly agent_admissions: {
      readonly client_message_id: CodecTypes['pg/text@1']['output'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly id: CodecTypes['pg/uuid@1']['output'];
      readonly identity_id: CodecTypes['pg/text@1']['output'];
      readonly kind: CodecTypes['pg/text@1']['output'];
      readonly operation_id: CodecTypes['pg/text@1']['output'] | null;
      readonly payer: CodecTypes['pg/text@1']['output'];
      readonly quota_refunded_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly quota_reserved_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
      readonly quota_usage_date: CodecTypes['pg/date-string@1']['output'] | null;
      readonly rejection_reason: CodecTypes['pg/text@1']['output'] | null;
      readonly request_digest: CodecTypes['pg/text@1']['output'];
      readonly session_id: CodecTypes['pg/text@1']['output'];
      readonly state: CodecTypes['pg/text@1']['output'];
    };
    readonly agent_open_operations: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['output'];
      readonly operation_id: CodecTypes['pg/text@1']['output'];
    };
    readonly agent_settlements: {
      readonly last_usage_seq: CodecTypes['pg/int8number@1']['output'];
      readonly operation_id: CodecTypes['pg/text@1']['output'];
      readonly settled_at: CodecTypes['pg/timestamptz-string@1']['output'] | null;
    };
    readonly pi_list_values: {
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly namespace: CodecTypes['pg/text@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly session_id: CodecTypes['pg/text@1']['output'];
      readonly value: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly pi_records: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly kind: 'entry' | 'usage';
      readonly payload: CodecTypes['pg/jsonb@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly session_id: CodecTypes['pg/text@1']['output'];
    };
    readonly pi_scalar_values: {
      readonly key: CodecTypes['pg/text@1']['output'];
      readonly namespace: CodecTypes['pg/text@1']['output'];
      readonly seq: CodecTypes['pg/int8number@1']['output'];
      readonly session_id: CodecTypes['pg/text@1']['output'];
      readonly value: CodecTypes['pg/jsonb@1']['output'] | null;
    };
    readonly pi_sessions: {
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly metadata: CodecTypes['pg/jsonb@1']['output'];
      readonly next_seq: CodecTypes['pg/int8number@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly agent_admissions: {
      readonly client_message_id: CodecTypes['pg/text@1']['input'];
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly id: CodecTypes['pg/uuid@1']['input'];
      readonly identity_id: CodecTypes['pg/text@1']['input'];
      readonly kind: CodecTypes['pg/text@1']['input'];
      readonly operation_id: CodecTypes['pg/text@1']['input'] | null;
      readonly payer: CodecTypes['pg/text@1']['input'];
      readonly quota_refunded_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly quota_reserved_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
      readonly quota_usage_date: CodecTypes['pg/date-string@1']['input'] | null;
      readonly rejection_reason: CodecTypes['pg/text@1']['input'] | null;
      readonly request_digest: CodecTypes['pg/text@1']['input'];
      readonly session_id: CodecTypes['pg/text@1']['input'];
      readonly state: CodecTypes['pg/text@1']['input'];
    };
    readonly agent_open_operations: {
      readonly created_at: CodecTypes['pg/timestamptz-string@1']['input'];
      readonly operation_id: CodecTypes['pg/text@1']['input'];
    };
    readonly agent_settlements: {
      readonly last_usage_seq: CodecTypes['pg/int8number@1']['input'];
      readonly operation_id: CodecTypes['pg/text@1']['input'];
      readonly settled_at: CodecTypes['pg/timestamptz-string@1']['input'] | null;
    };
    readonly pi_list_values: {
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly namespace: CodecTypes['pg/text@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly session_id: CodecTypes['pg/text@1']['input'];
      readonly value: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly pi_records: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly kind: 'entry' | 'usage';
      readonly payload: CodecTypes['pg/jsonb@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly session_id: CodecTypes['pg/text@1']['input'];
    };
    readonly pi_scalar_values: {
      readonly key: CodecTypes['pg/text@1']['input'];
      readonly namespace: CodecTypes['pg/text@1']['input'];
      readonly seq: CodecTypes['pg/int8number@1']['input'];
      readonly session_id: CodecTypes['pg/text@1']['input'];
      readonly value: CodecTypes['pg/jsonb@1']['input'] | null;
    };
    readonly pi_sessions: {
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly metadata: CodecTypes['pg/jsonb@1']['input'];
      readonly next_seq: CodecTypes['pg/int8number@1']['input'];
    };
  };
};
export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly agent_admissions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'uuid';
                  readonly codecId: 'pg/uuid@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'uuidv7()' };
                };
                readonly session_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly client_message_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly operation_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly identity_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly payer: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly request_digest: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly state: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'pending'>;
                  };
                };
                readonly rejection_reason: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly quota_usage_date: {
                  readonly nativeType: 'date';
                  readonly codecId: 'pg/date-string@1';
                  readonly nullable: true;
                };
                readonly quota_reserved_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
                readonly quota_refunded_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['operation_id'] },
                { readonly columns: readonly ['session_id', 'client_message_id'] },
              ];
              indexes: readonly [
                {
                  readonly name: 'agent_admissions_unresolved_4731a1b2';
                  readonly prefix: 'agent_admissions_unresolved';
                  readonly columns: readonly ['kind', 'created_at'];
                  readonly where: "state IN ('pending', 'accepted')";
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent_admissions';
                    readonly columns: readonly ['session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly agent_open_operations: {
              columns: {
                readonly operation_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly created_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['operation_id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent_open_operations';
                    readonly columns: readonly ['operation_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent_admissions';
                    readonly columns: readonly ['operation_id'];
                  };
                },
              ];
            };
            readonly agent_settlements: {
              columns: {
                readonly operation_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly last_usage_seq: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8number@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int8number@1', -1>;
                  };
                };
                readonly settled_at: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-string@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['operation_id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'agent_settlements_unsettled_3325215f';
                  readonly prefix: 'agent_settlements_unsettled';
                  readonly columns: readonly ['operation_id'];
                  readonly where: 'settled_at IS NULL';
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent_settlements';
                    readonly columns: readonly ['operation_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'agent_admissions';
                    readonly columns: readonly ['operation_id'];
                  };
                },
              ];
            };
            readonly pi_list_values: {
              columns: {
                readonly session_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly namespace: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly seq: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8number@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['session_id', 'namespace', 'key', 'seq'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_list_values';
                    readonly columns: readonly ['session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pi_records: {
              columns: {
                readonly session_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly seq: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8number@1';
                  readonly nullable: false;
                };
                readonly kind: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly payload: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['session_id', 'id'] };
              uniques: readonly [{ readonly columns: readonly ['session_id', 'seq'] }];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_records';
                    readonly columns: readonly ['session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pi_scalar_values: {
              columns: {
                readonly session_id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly namespace: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly key: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly seq: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8number@1';
                  readonly nullable: false;
                };
                readonly value: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: true;
                };
              };
              primaryKey: { readonly columns: readonly ['session_id', 'namespace', 'key'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_scalar_values';
                    readonly columns: readonly ['session_id'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'pi_sessions';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly pi_sessions: {
              columns: {
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly metadata: {
                  readonly nativeType: 'jsonb';
                  readonly codecId: 'pg/jsonb@1';
                  readonly nullable: false;
                };
                readonly next_seq: {
                  readonly nativeType: 'int8';
                  readonly codecId: 'pg/int8number@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int8number@1', 0>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
          };
          readonly valueSet: {
            readonly RecordKind: {
              readonly kind: 'valueSet';
              readonly values: readonly ['entry', 'usage'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly pi_sessions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PiSession';
    };
    readonly pi_records: { readonly namespace: 'public' & NamespaceId; readonly model: 'PiRecord' };
    readonly pi_scalar_values: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PiScalarValue';
    };
    readonly pi_list_values: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'PiListValue';
    };
    readonly agent_admissions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AgentAdmission';
    };
    readonly agent_open_operations: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AgentOpenOperation';
    };
    readonly agent_settlements: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'AgentSettlement';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly AgentAdmission: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/uuid@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly clientMessageId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly operationId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly identityId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly payer: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly requestDigest: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly rejectionReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly quotaUsageDate: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/date-string@1' };
              };
              readonly quotaReservedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
              readonly quotaRefundedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PiSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agent_admissions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly sessionId: { readonly column: 'session_id' };
                readonly clientMessageId: { readonly column: 'client_message_id' };
                readonly kind: { readonly column: 'kind' };
                readonly operationId: { readonly column: 'operation_id' };
                readonly identityId: { readonly column: 'identity_id' };
                readonly payer: { readonly column: 'payer' };
                readonly requestDigest: { readonly column: 'request_digest' };
                readonly state: { readonly column: 'state' };
                readonly rejectionReason: { readonly column: 'rejection_reason' };
                readonly createdAt: { readonly column: 'created_at' };
                readonly quotaUsageDate: { readonly column: 'quota_usage_date' };
                readonly quotaReservedAt: { readonly column: 'quota_reserved_at' };
                readonly quotaRefundedAt: { readonly column: 'quota_refunded_at' };
              };
            };
          };
          readonly AgentOpenOperation: {
            readonly fields: {
              readonly operationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly admission: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AgentAdmission';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['operationId'];
                  readonly targetFields: readonly ['operationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agent_open_operations';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly operationId: { readonly column: 'operation_id' };
                readonly createdAt: { readonly column: 'created_at' };
              };
            };
          };
          readonly AgentSettlement: {
            readonly fields: {
              readonly operationId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastUsageSeq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8number@1' };
              };
              readonly settledAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-string@1';
                };
              };
            };
            readonly relations: {
              readonly admission: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'AgentAdmission';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['operationId'];
                  readonly targetFields: readonly ['operationId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'agent_settlements';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly operationId: { readonly column: 'operation_id' };
                readonly lastUsageSeq: { readonly column: 'last_usage_seq' };
                readonly settledAt: { readonly column: 'settled_at' };
              };
            };
          };
          readonly PiListValue: {
            readonly fields: {
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly namespace: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly seq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8number@1' };
              };
              readonly value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PiSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pi_list_values';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly sessionId: { readonly column: 'session_id' };
                readonly namespace: { readonly column: 'namespace' };
                readonly key: { readonly column: 'key' };
                readonly seq: { readonly column: 'seq' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
          readonly PiRecord: {
            readonly fields: {
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly seq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8number@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PiSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pi_records';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly sessionId: { readonly column: 'session_id' };
                readonly id: { readonly column: 'id' };
                readonly seq: { readonly column: 'seq' };
                readonly kind: { readonly column: 'kind' };
                readonly payload: { readonly column: 'payload' };
              };
            };
          };
          readonly PiScalarValue: {
            readonly fields: {
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly namespace: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly key: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly seq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8number@1' };
              };
              readonly value: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'PiSession';
                };
                readonly cardinality: 'N:1';
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'pi_scalar_values';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly sessionId: { readonly column: 'session_id' };
                readonly namespace: { readonly column: 'namespace' };
                readonly key: { readonly column: 'key' };
                readonly seq: { readonly column: 'seq' };
                readonly value: { readonly column: 'value' };
              };
            };
          };
          readonly PiSession: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly metadata: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/jsonb@1' };
              };
              readonly nextSeq: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int8number@1' };
              };
            };
            readonly relations: Record<string, never>;
            readonly storage: {
              readonly table: 'pi_sessions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly metadata: { readonly column: 'metadata' };
                readonly nextSeq: { readonly column: 'next_seq' };
              };
            };
          };
        };
        readonly enum: {
          readonly RecordKind: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'entry'; readonly value: 'entry' },
              { readonly name: 'usage'; readonly value: 'usage' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
