import assert from "node:assert/strict";
import test from "node:test";
import { setImmediate } from "node:timers/promises";
import { BACKGROUND_CONTEXT } from "@earendil-works/pi-agent-core/harness/context";
import { searchNearby } from "../src/search-nearby.ts";
import { executeTool, fixture } from "./native-tool-fixture.ts";
import { catalogClock, pendingCatalog } from "./catalog-clock.ts";
void test("nearby total deadline expires during native retry backoff", async (context) => {
  catalogClock(context);
  const transport = pendingCatalog(4);
  const { repo, toolContext } = await fixture(transport.fetch);
  context.after(async () => { context.mock.timers.runAll(); await repo.close(BACKGROUND_CONTEXT); });
  let finished = false;
  const executed = executeTool(toolContext, "search_nearby", { location: "Kyoto" }, [searchNearby]).then((result) => { finished = true; return result; });
  await transport.received(0);
  context.mock.timers.tick(25_000); await setImmediate();
  context.mock.timers.tick(2_000); await transport.received(1);
  context.mock.timers.tick(25_000); await setImmediate();
  context.mock.timers.tick(2_000); const geocode = await transport.received(2);
  context.mock.timers.tick(24_000);
  geocode.respond(Response.json({ candidates: [{ id: "kyoto", label: "Kyoto", name: "Kyoto", lat: 35, lng: 135, kind: "city", source: "seed" }] }));
  const nearby = await transport.received(3);
  context.mock.timers.tick(6_000);
  nearby.respond(new Response("Unavailable", { status: 503 })); await setImmediate();
  context.mock.timers.tick(1_000); await setImmediate();
  const finishedAtDeadline = finished;
  context.mock.timers.tick(1_000); await executed;
  assert.equal(finishedAtDeadline, true, "Native nearby operation must finish at its 85-second total budget, including retry backoff");
});
